### ISSUE TITLE
Solution does not show up

### ISSUE THREAD

**Issue by Hellsender01** [Nalen98/AngryGhidra#10]
I am on **Ghidra v10.0**.
AngryGhidra found the solution but did not display it.
I have tested this on 3 binaries and all share the same problem.

![image](https://user-images.githubusercontent.com/57838029/128324516-c7e88726-b297-4b45-9dfa-aa4de0e889aa.png)

**Comment by Nalen98** [comment]
Seems your binary is position-independent. Angr will set base address to 0x400000 by deafult. So try to set base address of binary to 0x400000 in Ghidra (Memory Map) like this:

![Screenshot from 2021-08-05 17-28-37](https://user-images.githubusercontent.com/52778977/128367618-b9ca049f-20f3-47da-9de0-af1d573b2f01.png)

And run again with your settings. I've got this:

![Screenshot from 2021-08-05 17-32-29](https://user-images.githubusercontent.com/52778977/128367928-584dea09-3cdf-46c9-8c67-760987443b35.png)

**Comment by Hellsender01** [comment]
Oh ok! Now it's working fine. I think you should mention this somewhere.
