### ISSUE TITLE
Provide a pre-built version working with latest Ghidra 10.1 ?

### ISSUE THREAD

**Issue by bvernoux** [Nalen98/AngryGhidra#11]
Could you provide a pre-built version working with latest Ghidra 10.1 ?
- See https://github.com/NationalSecurityAgency/ghidra/releases/tag/Ghidra_10.1_build

**Comment by Nalen98** [comment]
Yes!
I built the new one, check out [here](https://github.com/Nalen98/AngryGhidra/releases/download/0.1/ghidra_10.1_AngryGhidra.zip).

**Comment by bvernoux** [comment]
Perfect it works fine (Note: I have generated my own version before and the build was perfect with Ghidra 10.1)
Could you add this version to the release https://github.com/Nalen98/AngryGhidra/releases/tag/0.1 (like that we can close this issue) ? (as there is no change to any files just a rebuild)

**Comment by Nalen98** [comment]
Sorry, maybe I don't get you cuz I already added this one as `ghidra_10.1_AngryGhidra.zip` asset. I built it with the newest version of Ghidra for now, and it works as expected.

**Comment by bvernoux** [comment]
Ha yes perfect thanks for all
I close the issue
