### ISSUE TITLE
Ghidra PCode Emulation with AngryGhidra

### ISSUE THREAD

**Issue by bvernoux** [Nalen98/AngryGhidra#12]
It will be a very nice feature to use Ghidra PCode Emulation with AngryGhidra (I suspect it will requires some changes in Angr ...) as today it requires to execute the code with native platform (also it does not seems possible to use QEmu which could be an alternative too)

**Comment by Nalen98** [comment]
Well, seems I'm not a contributor of angr project, but it's fact that angr uses unicorn engine as an emulation platform. And also it's not even possible to use Ghidra Pcode emulator as emulation engine here because it still can't support interbinary interaction (e.g., jumping between base executable and it's libraries) and syscall emulation as well. 
You can check out my [GhidraEmu](https://github.com/Nalen98/GhidraEmu) plugin to perform pcode emulation easily via gui.

**Comment by TrongChuongDao** [comment]
How I can start by AngryGhidra for Window 10. Thanks.

**Comment by Nalen98** [comment]
Hi, firstly you should run Ghidra and load this plugin as new Extension.
Check out this: https://github.com/Nalen98/AngryGhidra#installation.

**Comment by TrongChuongDao** [comment]
Thanks i will try .

Vào Th 6, 25 thg 3, 2022 lúc 15:45 Nalen98 ***@***.***> đã
viết:

**Comment by TrongChuongDao** [comment]
> Hi, firstly you should run Ghidra and load this plugin as new Extension. Check out this: https://github.com/Nalen98/AngryGhidra#installation.

I can''t to use for that. Thanks  
![image](https://user-images.githubusercontent.com/96568661/160323923-6706fc5f-696a-4be8-8db4-f040d3010dd2.png)

**Comment by Nalen98** [comment]
You should build this plugin with the latest Ghidra as you use (10.1.2). Or you can get it [here](https://github.com/Nalen98/AngryGhidra/releases/download/0.1/ghidra_10.1.2_AngryGhidra.zip), I built it

**Comment by TrongChuongDao** [comment]
Can you make a video for me please. I really still can't load them when I go to Install Extension but when we go to load Ghidra extension it can't really load them. Thanks. I run on windows 10

**Comment by Nalen98** [comment]
If you already loaded this plugin as Ghidra `File → Install Extensions...` and you've still missed that, check out this issue please, maybe it's gonna help you
https://github.com/Nalen98/AngryGhidra/issues/3#issuecomment-709381700

**Comment by TrongChuongDao** [comment]
> If you already loaded this plugin as Ghidra `File → Install Extensions...` and you've still missed that, check out this issue please, maybe it's gonna help you [#3 (comment)](https://github.com/Nalen98/AngryGhidra/issues/3#issuecomment-709381700)

Thanks I still can't. Thanks very much.

**Comment by Nalen98** [comment]
Show me your error message please or describe this incident more verbose, where it's falling

**Comment by TrongChuongDao** [comment]
![image](https://user-images.githubusercontent.com/96568661/160978477-e06afadc-142c-4c7f-a330-00455048f6dd.png). I can''t see plugin . Thanks.

**Comment by Nalen98** [comment]
Cuz you should press "plus" as adding new extension dialog. And choose file of AngryGhidra plugin (releases). After that Ghidra will ask you to restart the program.

**Comment by TrongChuongDao** [comment]
> Cuz you should press "plus" as adding new extension dialog. And choose file of AngryGhidra plugin (releases). After that Ghidra will ask you to restart the program.

![image](https://user-images.githubusercontent.com/96568661/161190575-b27ab906-0385-4dc7-9c30-325f401585f9.png)
![image](https://user-images.githubusercontent.com/96568661/161190612-356e1c04-ae33-4511-ad6a-3335d6f22d5e.png)
 Can''t load. Thanks

**Comment by Nalen98** [comment]
> You should build this plugin with the latest Ghidra as you use (10.1.2). Or you can get it [here](https://github.com/Nalen98/AngryGhidra/releases/download/0.1/ghidra_10.1.2_AngryGhidra.zip), I built it

Download this build as I mentioned before and choose `ghidra_10.1.2_AngryGhidra.zip` in "Select extension" dialog

**Comment by TrongChuongDao** [comment]
I can do that. Thanks you very much,

Vào Th 6, 1 thg 4, 2022 vào lúc 17:46 Nalen98 ***@***.***>
đã viết:
