### ISSUE TITLE
Error to build with latest Ghidra 10.2.2 / Gradle 7.x

### ISSUE THREAD

**Issue by bvernoux** [Nalen98/AngryGhidra#14]
AngryGhidra cannot be built with Ghidra 10.2.2 (which requires recent Java 17 with corresponding gradle 7.x) with some error in the build.gradle because it is not compatible with latest gradle 7.x (tested with gradle 7.3.2)

I have fixed the build.gradle using the following patch
[build.gradle.patch.zip](https://github.com/Nalen98/AngryGhidra/files/10106060/build.gradle.patch.zip)

**Comment by Nalen98** [comment]
Thanks. 
Fixed in https://github.com/Nalen98/AngryGhidra/commit/0318a9ffabcfb97d9a1f1881a4d0afe2687b2cf3 according to:
https://docs.gradle.org/current/userguide/upgrading_version_6.html#sec:configuration_removal

Checked on gradle 7.6
