### ISSUE TITLE
ghidra does not support python3

### ISSUE THREAD

**Issue by ItAllGoodMan** [Nalen98/AngryGhidra#2]
On windows, if the python3 path is set in the PATH environment variable, an error will still be reported when the angr script is executed, indicating that python2 should be upgraded to python3. How can I solve this problem?

**Comment by Nalen98** [comment]
Yes, Ghidra doesn't support Python3 cause It uses Jython 2.x, so plugin works on your system interpreter (python3) and Ghidra appears only as a data provider for angr script and doesn't directly participate. The plugin uses ProcessBuilder and calls the command ``python3 angryghidra.py angr_options.json`` (the last one is generated by the plugin based on your input data from GUI), and It's the only way to bypass Ghidra's restrictions. 
So, if you set the PATH variable correctly and typing ``python3`` in your command prompt manually running python3 shell It's gonna work correctly.
Truly, I've checked plugin on Windows too and It worked well.

Maybe You're trying to run angryghidra.py from Ghidra's Script Manager? It's not a good idea... If so, go to ``Window -> AngryGhidraPlugin`` and use it.

**Comment by ItAllGoodMan** [comment]
OK, the problem has been solved, thank you for your careful answer
