### ISSUE TITLE
Can't find context menu entry

### ISSUE THREAD

**Issue by gabriele-costa** [Nalen98/AngryGhidra#3]
I installed the extension following the README instructions. The procedure completes successfully and I am asked to restart Ghidra. However, when I open a project I can't find the context menu with the extension commands (as in the animated GIF).
I am using Ghidra 9.1.2.

**Comment by Nalen98** [comment]
Context menu is aviable only for disassembled listing view. If plugin was installed succesfully conext menu must be aviable too. AngryGhidraPopupMenu.java is responsible for this.

**Comment by gabriele-costa** [comment]
Actually the plugin seems to be installed (see picture 1) but when I do right click on the disassembled listing the entry is missing (picture 2). Can you suggest me a way to debug the extension's Java code to see whether it is executed properly? Or is there something else I can check?

Thank you

![Schermata del 2020-10-15 11-30-41](https://user-images.githubusercontent.com/10499254/96105217-143af680-0eda-11eb-8c6f-e571ce6b575e.png)
![Schermata del 2020-10-15 11-31-36](https://user-images.githubusercontent.com/10499254/96105245-1bfa9b00-0eda-11eb-8aeb-8eec0e1440df.png)

**Comment by Nalen98** [comment]
Could you please check AngryGhidraPlugin persistence in Ghidra Window? Is it present? I'm going to investigate this thing.

![image](https://user-images.githubusercontent.com/52778977/96114574-77368880-0eee-11eb-9ac2-f740080825b7.png)

Did you got these windows when you've installed plugin?

![image](https://user-images.githubusercontent.com/52778977/96116661-7f43f780-0ef1-11eb-8609-38808e4b383c.png)

![image](https://user-images.githubusercontent.com/52778977/96116770-a8648800-0ef1-11eb-8e7f-299dfdeae5e3.png)

**Comment by gabriele-costa** [comment]
No, I don't have it. Seems like the extension is disabled

![Schermata del 2020-10-15 14-24-13](https://user-images.githubusercontent.com/10499254/96122692-2de83800-0ef2-11eb-9abb-8697e8e03955.png)

**Comment by Nalen98** [comment]
Ok, I suppose you missied this one. Try ``File -> Configure -> Experemental``:

![Screenshot from 2020-10-15 10-48-43](https://user-images.githubusercontent.com/52778977/96146470-fcca3080-0f0e-11eb-8ae5-69b79cd6e739.png)

Press "configure" and choose AngryGhidraPlugin checkbox:

![Screenshot from 2020-10-15 10-52-59](https://user-images.githubusercontent.com/52778977/96146754-503c7e80-0f0f-11eb-8401-df4966337f4f.png)

**Comment by Nalen98** [comment]
Let me know if it'll work for you

**Comment by gabriele-costa** [comment]
That was it! Thank you very much

**Comment by Nalen98** [comment]
You're welcome
