### ISSUE TITLE
Ghidra 9.2 support?

### ISSUE THREAD

**Issue by ma77carpenter** [Nalen98/AngryGhidra#4]
Will this plugin have a 9.2.0 release soon?
I've tried the simple "change-the-version-number-in-extension.properties" trick, but can't seem to get this to work.  My team is building an ISO and including tools like this one, but we want to use Ghidra 9.2 and our deadline is Tuesday.  If we can't get it in this version, perhaps we can add this tool in a future release.

Thanks,
Matt

**Comment by Nalen98** [comment]
Hi Matt,
Check out [the latest release](https://github.com/Nalen98/AngryGhidra/releases/latest) for ghidra v9.2.
