### ISSUE TITLE
Python process creation fails silently due to "python3" argument

### ISSUE THREAD

**Issue by meromwolff** [Nalen98/AngryGhidra#5]
Hi,

In the runAngr method that's part of the AngryGhidraProvider.java file, a python3.exe process is created.
Since this executable is not available for all python versions > 3.4 (these versions contain the "regular" python.exe), executing the plugin will just end up always printing the
"No solution found" string immediately. 
That said, maybe a check for the python version could be added prior to the process creation so the user would not be left wondering why the plugin cant find any solution...

Thanks

**Comment by Nalen98** [comment]
Hi!
Try current master and let me know if it works fine.

**Comment by meromwolff** [comment]
Great - works as expected,
Thanks for the quick fix!
