### ISSUE TITLE
10.0.0 support / not working

### ISSUE THREAD

**Issue by bravosierra99** [Nalen98/AngryGhidra#6]
I appear to have installed the extension but do not see it.  I looked at the previous issue and went through those steps but it's not in the experimental plugins section any more, so it doesn't seem to apply.

![image](https://user-images.githubusercontent.com/8898577/120674568-3762e800-c462-11eb-9a1a-b06c859fabe4.png)
![image](https://user-images.githubusercontent.com/8898577/120674659-4f3a6c00-c462-11eb-9e29-39384cb270da.png)
![image](https://user-images.githubusercontent.com/8898577/120674699-5bbec480-c462-11eb-857f-550fb464db1e.png)

Any help would be appreciated!  Thank you.

**Comment by bravosierra99** [comment]
for what it's worth I just tried with 9.2.4 and it didn't appear to work there either.  I used the cloning into Ghidra/Extensions method of installing.

**Comment by Nalen98** [comment]
Hi!
Seems it's better to build extension with gradle and add it with ``File → Install Extensions...`` menu option. Or you can download release build from [here](https://github.com/Nalen98/AngryGhidra/releases/tag/0.1) for ghidra 10-BETA.

And as you can see, experimental configure menu works ok:

![image_2021-06-06_15-46-45](https://user-images.githubusercontent.com/52778977/120925321-c54c0680-c6e0-11eb-8a95-4716977bee14.png)

**Comment by bravosierra99** [comment]
Thank you for responding.  I was able to download the precompiled plugin and have it show up (not under experimental for me, it shows up normally)

If I understand your plugin correctly it should launch a python to run angr.  However, this does not happen for me (python is on my path).  The plugin simply immediately tells me that a solution cannot be found.  Is there an easy way to enable debugging for this?  I'm guessing I have to do the whole  Ghidra from source debugging thing.  I'll see if I can find some time to do that.

**Comment by Nalen98** [comment]
You should check that "python3" is in your enviroment like this:
```
C:\Users\Nalen>python3
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr
>>>
```
If plugin was installed correctly this one should work.
