### ISSUE TITLE
9.2,9.2.1 / not working

### ISSUE THREAD

**Issue by Dontacos21** [Nalen98/AngryGhidra#7]
I tried "firlight" with the same settings, but I get "Solution Not Found".
I feel like AngryGhidra is not working.
What should I do?
I'm running Windows 10 Pro.

- [ ] 
<img width="695" alt="キャプチャ" src="https://user-images.githubusercontent.com/85323044/120730199-e4e60200-c51b-11eb-9198-804e4c737c3f.PNG">

Any help would be appreciated! Thank you!

**Comment by Nalen98** [comment]
Hi!
Did you install angr for py3?

**Comment by Dontacos21** [comment]
Yes!
When I run it, it works fine.

```
C:\Users\hoge>python
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr
>>>
```

**Comment by Nalen98** [comment]
Did you build with gradle or download from release builds?

**Comment by Dontacos21** [comment]
I downloaded "ghidra_9.2.1_AngryGhidra.zip" from the release.
After that, I installed it in Ghidra using "File" -> "Install Extensions".

**Comment by Nalen98** [comment]
Well, seems I got what the root of all evil is. The plugin works with env. var "python3", not "python". This thing was done because of many people have "python" env equivalent python v2.x and "python3" env with python v3.x respectively. So, cuz angr supports python3 only, I've decided to do like this.
So try to set "python3" env and get this result:
```
C:\Users\Nalen>python3
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr
>>>
```

**Comment by Dontacos21** [comment]
I set it up the same way, but the result was the same: "Solution Not Found".

```
C:\Users\hoge>python3
Python 3.9.5 (tags/v3.9.5:0a7dcbd, May  3 2021, 17:27:52) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import angr
>>>
```

**Comment by Dontacos21** [comment]
I'm sorry.
I reviewed the settings and it works.
Thank you very much!!!
![angryghidra](https://user-images.githubusercontent.com/85323044/120933056-606dcc00-c733-11eb-9c77-395e3995a734.PNG)

**Comment by Nalen98** [comment]
You're welcome
