### ISSUE TITLE
Not found Ghidra Extension

### ISSUE THREAD

**Issue by gjxo12** [Nalen98/AngryGhidra#8]
Hi, I have one Issue of your good open Source.

here is my Ghidra Version Information. 

![image](https://user-images.githubusercontent.com/15341381/123750232-4d44bb00-d8f1-11eb-98d2-c65784dbf55d.png)

I download your Release Extension a 'ghidra_9.2_AngryGhidra.zip'.

but AngryGhidra Extension not found..

![image](https://user-images.githubusercontent.com/15341381/123751675-f17b3180-d8f2-11eb-9554-63610456186e.png)

Oh, and I tried install Extension a 'AngryGhidra-master.jar' with in ghidra_9.2_AngryGhidra\AngryGhidra-master\lib

but, installaion error occured. Messaging is not a valid Ghidra Extensioin...

![image](https://user-images.githubusercontent.com/15341381/123752886-3bb0e280-d8f4-11eb-93d3-12538daf27d1.png)

can you help me this problem?

**Comment by Nalen98** [comment]
Hi!
Yeah, you're right, 10.0 BETA plugin release is not compatible with new 10 ghidra version, check out [this one](https://github.com/Nalen98/AngryGhidra/releases/download/0.1/ghidra_10.0_AngryGhidra.zip) for 10.0.

**Comment by gjxo12** [comment]
Hi, Thank you for your response.

As recommended, I checked the versions below.

![image](https://user-images.githubusercontent.com/15341381/124384649-4b259680-dd0d-11eb-8c5b-d9e2aa91f237.png)

10.0 Beta plugin of AngryGhidra, two Ghidra version, 10.0 / 9.2.4 REPUBLIC Using OpenJDK 12

But Ghidra 10.0 REPUBLIC and 10.0 Beta plugin of AngryGhidra cannot install Extention plugin
and Likewise, Ghidra 9.2.4 REPUBLIC and 10.0 Beta plugin of AngryGhidra is same...

![image](https://user-images.githubusercontent.com/15341381/124384845-19f99600-dd0e-11eb-922a-4f2aa1d037e3.png)

Is there any other way to solve this problem? or Is there something I missed?

Thank you

**Comment by Nalen98** [comment]
You don't need to unpack plugin zip archive, you should add .zip with ``File → Install Extensions``. [Here](https://github.com/Nalen98/AngryGhidra/releases/tag/0.1) you can download releases for almost each versions of ghidra and they must be compatible.

**Comment by gjxo12** [comment]
Oh.. Thank you for your rapid response...

I was stupid

Have a nice day!!
